apiVersion: v1
kind: ConfigMap
metadata:
  name: mtg-rag-config
  namespace: mtg-rag
data:
  DD_TRACE_ENABLED: "true"
  DD_METRICS_ENABLED: "true"
  DD_LOGS_JSON: "true"
  DD_LOGS_INJECTION: "true"
  DD_SERVICE: "mtg-rag-api"
  DD_ENV: "minikube"
  DD_VERSION: "0.1.0"
  LOG_LEVEL: "INFO"
