apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mtg-rag
resources:
  - ../../base
  - datadog-agent.yaml

patches:
  - path: configmap-datadog.yaml
  - path: api-datadog.yaml
