apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: mtg-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-data
  namespace: mtg-rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
